/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.gelatowave.mobile;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int flashbuttonoff=0x7f020000;
        public static final int flashbuttonon=0x7f020001;
        public static final int icon=0x7f020002;
        public static final int overlay=0x7f020003;
    }
    public static final class id {
        public static final int RelativeLayout1=0x7f060000;
        public static final int flashButton=0x7f060003;
        public static final int overlayImage=0x7f060002;
        public static final int preview_view=0x7f060001;
    }
    public static final class layout {
        public static final int scanner=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f050000;
    }
    public static final class xml {
        public static final int config=0x7f040000;
    }
}
